-- AlterTable
ALTER TABLE "Paciente" ALTER COLUMN "p_cpf" SET DATA TYPE TEXT,
ALTER COLUMN "p_cpf_digits" SET DATA TYPE TEXT,
ALTER COLUMN "p_rg" SET DATA TYPE TEXT,
ALTER COLUMN "p_fone" SET DATA TYPE TEXT;
